use eventmate;
INSERT INTO event (EventID, Name, Club, Status, Date, Venue, Description, Fee, OD, Team, Contact, RegistrationLink, MaxLimit, tags)
VALUES
('24CDCDVJ', 'Tech Symposium', 'Tech Club', 'open', '2024-05-15', 'Auditorium', 'Join us for a day of tech talks, workshops, and networking. Learn about the latest trends in technology and connect with industry professionals.', 0.00, 1, 5, 'techclub@example.com', 'https://example.com/tech-symposium', 100, 'technology, symposium, workshop, networking, industry, professionals, trends, talks, IT, gadgets, innovation, coding, programming, software, hardware'),
('25GHIJQL', 'Sports Meet', 'Sports Club', 'upcoming', '2024-06-20', 'Sports Ground', 'Get ready for a day full of sports activities and competitions. Show off your skills and compete for exciting prizes.', 0.00, 0, 3, 'sportsclub@example.com', 'https://example.com/sports-meet', 200, 'sports, meet, competition, games, prizes, athletes, sportsmanship, skills, fitness, outdoor, indoor, team, individual, fun'),
('26KLMNOP', 'Cultural Night', 'Cultural Club', 'upcoming', '2024-07-10', 'Open Air Theater', 'Experience a night of cultural extravaganza with dance performances, music, and delicious food. Join us for an unforgettable evening.', 0.00, 1, 4, 'culturalclub@example.com', 'https://example.com/cultural-night', 150, 'cultural, night, dance, music, food, performance, tradition, entertainment, art, talent, diversity, celebration, community, fun'),
('27PQRSTUV', 'Career Fair', 'Placement Cell', 'upcoming', '2024-08-05', 'Campus Auditorium', 'Explore job opportunities, interact with recruiters, and attend career development workshops. Get ready to kickstart your career.', 0.00, 0, 2, 'placementcell@example.com', 'https://example.com/career-fair', 300, 'career, fair, job, opportunity, recruitment, workshop, development, resume, interview, skills, networking, professionals, companies, growth'),
('28STUVWXY', 'Science Expo', 'Science Club', 'upcoming', '2024-09-15', 'Science Building', 'Discover the wonders of science through interactive exhibits, experiments, and demonstrations. A must-visit for science enthusiasts of all ages.', 0.00, 1, 5, 'scienceclub@example.com', 'https://example.com/science-expo', 150, 'science, expo, exhibit, experiment, demonstration, discovery, innovation, technology, education, learning, STEM, curiosity, fun, interactive'),
('29YZABCDW', 'Literary Fest', 'Literary Club', 'upcoming', '2024-10-20', 'Library Hall', 'Celebrate the world of literature with poetry readings, book discussions, and storytelling sessions. Immerse yourself in the magic of words.', 0.00, 0, 3, 'literaryclub@example.com', 'https://example.com/literary-fest', 200, 'literary, fest, literature, poetry, books, reading, discussion, storytelling, words, language, culture, creativity, imagination, expression');

INSERT INTO event (EventID, Name, Club, Status, Date, Venue, Description, Fee, OD, Team, Contact, RegistrationLink, MaxLimit, tags)
VALUES
('30CDEFGH', 'Art Exhibition', 'Art Club', 'upcoming', '2024-11-10', 'Art Gallery', 'Explore the world of art with a stunning exhibition featuring paintings, sculptures, and installations by talented artists. Immerse yourself in creativity and beauty.', 0.00, 1, 4, 'artclub@example.com', 'https://example.com/art-exhibition', 100, 'art, exhibition, painting, sculpture, installation, artist, creativity, beauty, gallery, visual, expression, talent, culture, showcase'),
('31EFGHIJK', 'Music Concert', 'Music Club', 'upcoming', '2024-12-05', 'Outdoor Stage', 'Enjoy a night of melodious music and live performances by talented musicians. Join us for an unforgettable musical experience under the stars.', 0.00, 0, 5, 'musicclub@example.com', 'https://example.com/music-concert', 200, 'music, concert, performance, live, band, musician, melody, rhythm, song, entertainment, stage, outdoor, night, stars'),
('32GHIJKLM', 'Film Festival', 'Film Club', 'upcoming', '2025-01-20', 'Auditorium', 'Watch a curated selection of the best films from around the world. Experience the magic of cinema and explore diverse stories and cultures.', 0.00, 1, 3, 'filmclub@example.com', 'https://example.com/film-festival', 150, 'film, festival, cinema, movie, screening, international, story, culture, diversity, entertainment, art, magic, audience, experience'),
('33IJKLMNOP', 'Tech Hackathon', 'Tech Club', 'upcoming', '2025-02-15', 'Computer Lab', 'Join us for a 24-hour hackathon to solve real-world problems using technology. Compete with fellow tech enthusiasts and showcase your skills.', 0.00, 0, 5, 'techclub@example.com', 'https://example.com/tech-hackathon', 100, 'tech, hackathon, coding, programming, problem-solving, competition, innovation, technology, development, project, team, challenge, creativity, solution'),
('34KLMNOPQ', 'Fashion Show', 'Fashion Club', 'upcoming', '2025-03-10', 'Fashion Arena', 'Experience the glamour and style of a high-end fashion show featuring the latest trends and designs. Be inspired by the creativity and elegance of the fashion world.', 0.00, 1, 4, 'fashionclub@example.com', 'https://example.com/fashion-show', 150, 'fashion, show, glamour, style, trend, design, runway, model, clothing, elegance, creativity, inspiration, showcase, beauty'),
('35QRSTUVW', 'Food Festival', 'Culinary Club', 'upcoming', '2025-04-05', 'Food Court', 'Savor a variety of delicious dishes and culinary delights from around the world. Experience a gastronomic journey like never before.', 0.00, 0, 3, 'culinaryclub@example.com', 'https://example.com/food-festival', 200, 'food, festival, culinary, cuisine, dish, taste, flavor, gastronomy, world, culture, experience, delight, menu, chef'),
('36VWXYZAB', 'Dance Competition', 'Dance Club', 'upcoming', '2025-05-10', 'Dance Studio', 'Showcase your dance skills and creativity in a thrilling dance competition. Compete with the best and dazzle the audience with your performance.', 0.00, 1, 5, 'danceclub@example.com', 'https://example.com/dance-competition', 100, 'dance, competition, performance, showcase, talent, creativity, choreography, music, rhythm, stage, audience, entertainment, excitement, passion'),
('37YZABCDE', 'Science Fair', 'Science Club', 'upcoming', '2025-06-15', 'Science Building', 'Participate in exciting science experiments and demonstrations. Explore the wonders of science and learn through hands-on activities.', 0.00, 0, 2, 'scienceclub@example.com', 'https://example.com/science-fair', 300, 'science, fair, experiment, demonstration, hands-on, activity, learning, education, innovation, discovery, fun, curiosity, exploration, STEM'),
('38ZABCDEF', 'Debate Competition', 'Debate Club', 'upcoming', '2025-07-20', 'Debate Hall', 'Engage in thought-provoking debates on current issues and topics. Sharpen your argumentative skills and compete to be the best debater.', 0.00, 1, 3, 'debateclub@example.com', 'https://example.com/debate-competition', 200, 'debate, competition, argument, current issues, topics, skill, debate, debater, speech, persuasion, logic, reasoning, intellect, challenge'),
('39BCDEFGH', 'Photography Contest', 'Photography Club', 'upcoming', '2025-08-05', 'Gallery', 'Capture stunning images and showcase your photography skills in a friendly competition. Let your creativity and vision shine through your photographs.', 0.00, 0, 4, 'photographyclub@example.com', 'https://example.com/photography-contest', 150, 'photography, contest, competition, image, creativity, vision, skill, photographer, capture, moment, art, beauty, showcase, talent');

INSERT INTO event (EventID, Name, Club, Status, Date, Venue, Description, Fee, OD, Team, Contact, RegistrationLink, MaxLimit, tags)
VALUES
('40ABCDEFGHIJ', 'Charity Run', 'Social Service Club', 'upcoming', '2025-09-10', 'College Campus', 'Join us for a charity run to raise funds for a noble cause. Run for a healthier community and make a difference in the lives of those in need.', 0.00, 1, 5, 'socialserviceclub@example.com', 'https://example.com/charity-run', 100, 'charity, run, fundraising, community, health, cause, noble, difference, support, donate, charity event, fitness, exercise, awareness'),
('41BCDEFGHIJK', 'Gaming Tournament', 'Gaming Club', 'upcoming', '2025-10-15', 'Gaming Arena', 'Compete in thrilling gaming battles and showcase your gaming skills. Win exciting prizes and enjoy a day of gaming fun.', 0.00, 0, 3, 'gamingclub@example.com', 'https://example.com/gaming-tournament', 200, 'gaming, tournament, competition, game, battle, skill, prize, fun, gaming club, video game, esports, player, challenge, excitement'),
('42CDEFGHIJKL', 'Yoga Workshop', 'Wellness Club', 'upcoming', '2025-11-10', 'Wellness Center', 'Experience the benefits of yoga and learn various yoga techniques. Improve your physical and mental well-being in a relaxing environment.', 0.00, 1, 4, 'wellnessclub@example.com', 'https://example.com/yoga-workshop', 100, 'yoga, workshop, wellness, health, relaxation, benefits, technique, physical, mental, well-being, exercise, meditation, mindfulness, fitness'),
('43DEFGHIJKLM', 'Entrepreneurship Summit', 'Entrepreneurship Club', 'upcoming', '2025-12-05', 'Startup Hub', 'Join us for a summit dedicated to entrepreneurship. Listen to inspiring success stories, attend workshops, and network with fellow entrepreneurs.', 0.00, 0, 5, 'entrepreneurshipclub@example.com', 'https://example.com/entrepreneurship-summit', 200, 'entrepreneurship, summit, entrepreneur, success, workshop, networking, startup, business, innovation, idea, venture, inspiration, mentorship, growth'),
('44EFGHIJKLMN', 'Environmental Cleanup Drive', 'Environment Club', 'upcoming', '2026-01-20', 'Local Park', 'Participate in a cleanup drive to protect the environment and promote cleanliness. Contribute to a greener and cleaner planet.', 0.00, 1, 3, 'environmentclub@example.com', 'https://example.com/cleanup-drive', 150, 'environmental, cleanup, drive, environment, cleanliness, green, planet, earth, sustainability, community, volunteer, action, awareness, conservation'),
('45FGHIJKLMNO', 'Fashion Design Workshop', 'Fashion Club', 'upcoming', '2026-02-15', 'Fashion Studio', 'Learn the art of fashion design from experts in the field. Develop your skills and creativity in designing clothing and accessories.', 0.00, 0, 4, 'fashionclub@example.com', 'https://example.com/fashion-design-workshop', 150, 'fashion, design, workshop, clothing, accessory, style, creativity, skill, designer, fashionista, trend, learn, art, expert'),
('46GHIJKLMNOP', 'Music Workshop', 'Music Club', 'upcoming', '2026-03-10', 'Music Room', 'Enhance your musical skills and knowledge in a workshop conducted by experienced musicians. Learn new techniques and explore different genres of music.', 0.00, 1, 5, 'musicclub@example.com', 'https://example.com/music-workshop', 100, 'music, workshop, musical, skill, knowledge, technique, genre, musician, learn, experience, music club, instrument, performance, practice'),
('47HIJKLMNOPQ', 'Health and Wellness Fair', 'Wellness Club', 'upcoming', '2026-04-05', 'Wellness Center', 'Discover ways to improve your health and well-being at our health and wellness fair. Get access to health screenings, workshops, and fitness activities.', 0.00, 0, 3, 'wellnessclub@example.com', 'https://example.com/health-wellness-fair', 200, 'health, wellness, fair, screening, workshop, fitness, activity, well-being, lifestyle, nutrition, exercise, mindfulness, holistic'),
('48IJKLMNOPQR', 'Science Quiz Competition', 'Science Club', 'upcoming', '2026-05-10', 'Science Building', 'Test your knowledge of science in a fun and challenging quiz competition. Compete with other science enthusiasts and win exciting prizes.', 0.00, 1, 3, 'scienceclub@example.com', 'https://example.com/science-quiz', 200, 'science, quiz, competition, knowledge, fun, challenge, science club, enthusiast, prize, question, answer, discovery, learning, education'),
('49JKLMNOPQRS', 'Drama Festival', 'Drama Club', 'upcoming', '2026-06-15', 'Outdoor Stage', 'Experience the magic of theater with captivating drama performances. Immerse yourself in stories brought to life on stage.', 0.00, 0, 4, 'dramaclub@example.com', 'https://example.com/drama-festival', 150, 'drama, festival, theater, performance, stage, story, character, act, drama club, play, audience, entertainment, emotion, expression');

INSERT INTO student (StudentID, Name, College, Year, Branch, Program, Password, tags)
VALUES
('22ABCD0129', 'Alice Smith', 'VIT', 2, 'Computer Science', 'B.Tech', 'password123', 'coding, technology, programming, music, dance, sports, reading, travel, photography, art'),
('23WXYZ1298', 'Bob Johnson', 'VIT', 3, 'Electronics and Communication', 'B.Tech', 'securepass456', 'coding, technology, robotics, music, movies, cooking, travel, gaming, photography, science'),
('21PQRS2345', 'Charlie Brown', 'VIT', 1, 'Mechanical Engineering', 'B.Tech', 'secretword789', 'drama, sports, music, dance, reading, writing, travel, gaming, art, photography'),
('20LMNO3456', 'David Miller', 'VIT', 4, 'Civil Engineering', 'B.Tech', 'pass1234', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history'),
('19EFGH4567', 'Eve Wilson', 'VIT', 2, 'Computer Science', 'B.Tech', 'password321', 'coding, technology, programming, music, dance, sports, reading, travel, photography, art');

INSERT INTO student (StudentID, Name, College, Year, Branch, Program, Password, tags)
VALUES
('22FGHI0123', 'Fiona Williams', 'VIT', 3, 'Electrical Engineering', 'B.Tech', 'password789', 'coding, technology, robotics, music, movies, cooking, travel, gaming, photography, science'),
('23JKLM2345', 'George Davis', 'VIT', 4, 'Computer Science', 'B.Tech', 'securepass321', 'coding, technology, programming, music, dance, sports, reading, travel, photography, art'),
('21NOPQ3456', 'Hannah Brown', 'VIT', 2, 'Information Technology', 'B.Tech', 'password456', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history'),
('20RSTU4567', 'Ivy Anderson', 'VIT', 1, 'Computer Science', 'B.Tech', 'secretword123', 'drama, sports, music, dance, reading, writing, travel, gaming, art, photography'),
('19VWXY5678', 'Jack Wilson', 'VIT', 3, 'Mechanical Engineering', 'B.Tech', 'pass4567', 'coding, technology, robotics, music, movies, cooking, travel, gaming, photography, science'),
('22YZAB6789', 'Kelly Lee', 'VIT', 2, 'Civil Engineering', 'B.Tech', 'password987', 'coding, technology, programming, music, dance, sports, reading, travel, photography, art'),
('23CDEF7890', 'Leo Martin', 'VIT', 4, 'Electronics and Communication', 'B.Tech', 'securepass654', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history'),
('21GHIJ8901', 'Mia Taylor', 'VIT', 1, 'Computer Science', 'B.Tech', 'password567', 'coding, technology, robotics, music, dance, sports, reading, travel, photography, art'),
('20KLMN9012', 'Noah White', 'VIT', 2, 'Electrical Engineering', 'B.Tech', 'secretword321', 'drama, sports, music, dance, reading, writing, travel, gaming, art, photography'),
('19OPQR0123', 'Olivia Clark', 'VIT', 3, 'Information Technology', 'B.Tech', 'pass7890', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history');

INSERT INTO student (StudentID, Name, College, Year, Branch, Program, Password, tags)
VALUES
('22STUV2345', 'Peter Wilson', 'VIT', 4, 'Mechanical Engineering', 'B.Tech', 'password567', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history'),
('23UVWX3456', 'Rachel Moore', 'VIT', 1, 'Computer Science', 'B.Tech', 'secretword321', 'drama, sports, music, dance, reading, writing, travel, gaming, art, photography'),
('21WXYZ4567', 'Samuel Baker', 'VIT', 2, 'Electrical Engineering', 'B.Tech', 'pass7890', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history'),
('20YZAB5678', 'Tina Young', 'VIT', 3, 'Computer Science', 'B.Tech', 'password123', 'coding, technology, robotics, music, dance, sports, reading, travel, photography, art'),
('19ZABC6789', 'Victor Turner', 'VIT', 2, 'Mechanical Engineering', 'B.Tech', 'securepass456', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history'),
('22BCDE7890', 'Wendy Harris', 'VIT', 3, 'Civil Engineering', 'B.Tech', 'password987', 'coding, technology, programming, music, dance, sports, reading, travel, photography, art'),
('23CDEF8901', 'Xavier Garcia', 'VIT', 1, 'Electronics and Communication', 'B.Tech', 'securepass654', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history'),
('21DEFG9012', 'Yvonne Martinez', 'VIT', 4, 'Computer Science', 'B.Tech', 'password789', 'coding, technology, programming, music, dance, sports, reading, travel, photography, art'),
('20EFGH0123', 'Zane Rodriguez', 'VIT', 1, 'Electrical Engineering', 'B.Tech', 'secretword234', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history'),
('19FGHI1234', 'Alice Smith', 'VIT', 3, 'Computer Science', 'B.Tech', 'password567', 'coding, technology, reading, travel, sports, music, movies, gaming, science, history');

